SmartTV.txt

`api-global.netflix.com`, `secure.netflix.com`, `ichnaea.netflix.com` have to be disabled, otherwise Netflix will not work.

Fixes Netflix

---

android-tracking.txt

cf-st.sc-cdn.net caused messages and embeds to not load.

Fix Snapchat

---

SmartTV.txt

`https://get.geo.opera.com/pub/opera/desktop/X/win/Opera_X_Setup_x64.exe` would be blocked otherwise

Allow downloading Opera

---

SmartTV.txt

There seems to be a version of "osb.samsungqbe.com" for every region. For me as a European user "osb-eusvc.samsungqbe.com" had to be added. The "kr"-version for Korea is already there, but I don't now about the US and other regions.

Add osb-eusvc.samsungqbe.com to SmartTV.txt

---

SmartTV.txt

As for many "services" there seem to be regional variants. This adds the EU version of the ACR-log (Automatic Content Recognition).
Source (among others and my own experience): https://sbmueller.github.io/post/pihole/

Add log-ingestion-eu.samsungacr.com to SmartTV.txt

---

SmartTV.txt

`ichnaea.netflix.com` doesn't seem to break Netflix anymore. I've had it blocked for over a week and Netflix still works on all the devices on my network. If someone else could confirm before this PR gets merged that'd be great!

Update Netflix default block list

---

SmartTV.txt

Hi there,
I don't know if this is intentional, but blocking `samsungosp.com` related domains will BREAK user authentication (i.e. logging into Samsung account)
I discovered this by accident with the similar issue:
https://imgur.com/gallery/9FxJ5
```
auth.samsungosp.com
us-auth2.samsungosp.com
```
People seem to also complain here:
https://www.reddit.com/r/pihole/comments/c8u0la/comment/esptp24
If this was not intentional, could you please unblock these domains by merging this pull request?
Otherwise, ignore this PR.
P.S. the same domains are also present in here:
https://github.com/Akamaru/Pi-Hole-Lists/pull/3
Thank you

Remove samsung authentication domains

---

SmartTV.txt

static-cdn.jtvnw.net is part of the CDN for twitch.tv and this blocked legit traffic for emojis, icons and static preview images.

Removed static-cdn.jtvnw.net

---

SmartTV-AGH.txt
SmartTV.txt
regex.list

Okay, so the situation is that AdGuard Home is now seemingly doing [an open rollcall for new lists to include in stock installations](https://github.com/AdguardTeam/AdGuardHome/issues/1325). Additionally, I became aware of some problems involving the Deezer smart-TV app and of a way to block LG TVs' ridiculous connection attempts to garbled domains, so I went for a twofer, and decided to fix the entries in your Pi-hole list version and to create an AGH list version on top of that, spending three days on the preparations.
Complete changelog:
* Created an AdGuard Home list version based on not only your smart-TV list, but also your Amazon Fire TV list and select entries from my game console list.
* Attempted to deal with https://github.com/Perflyst/PiHoleBlocklist/issues/29 to the best of …

Pretty big update

---

android-tracking.txt

Heya! Got a quick whitelist addition for you: `b-graph.facebook.com`
This domain is required for Facebook Pages Manager to be able to login.

Whitelist b-graph.facebook.com

---

SmartTV.txt

Netflix displays the error "We are having difficulty playing this title" 
Error appears within Nextflix app on STB when clicking play. Whitelisting resolves error, reproduces when white-list entry is removed.

Commented out  nrdp.nccp.netflix.com

---

SmartTV-AGH.txt
SmartTV.txt

This change requires proper router configuration to be trully effective, because the OS on this brand tries to avoid blocking with hard coded DNS server. The router has to block these requests or redirect them to Pi-hole.

Block Toshiba TV telemetry & tracking

---

SmartTV.txt

Even disabled on Sony interface, there is a connection every FIVE minutes!
One was already defined for Toshiba TV
It connects also to several *.netflix.com and *.nflximg.com but I don't use that crap...
I was able to block them with https://nextdns.io/?from=98ctfnjk

2 samba.tv

---

SmartTV-AGH.txt
SmartTV.txt

In the past few days, I've been in talks with the maintainer of OISD.nl, who has its own issue tracker for complaints about false positives, about making such false-positive lists for each of its individual filterlists, because I felt it'd be a big gamechanger for most hosts files. Which was indeed the case.
By going through https://dbl.oisd.nl/showme.php?show=unlisted&list=7730c77bcc21df13c6df8e75e5a54097 and seeing which ones that had any sort of explanation for their whitelisting, I've now implemented those with reasonable explanations here at the entries' source.

Went through OISD's whitelist pages

---

SmartTV-AGH.txt
SmartTV.txt

#110
When using this list, if you are connected to the network, a user would be unable to use the NFL Fantasy Football App.
Comment line out for blocking `api.nfl.com` since it is a required call for the application.
* fix(#110): Update SmartTV.txt
Allow users to use the NFL Fantasy Football mobile application.

Allow users to play fantasy football on NFL App

---

android-tracking.txt

This comes up often overnight with our Pixel phones. While federated learning is cool (https://ai.googleblog.com/2017/04/federated-learning-collaborative.html) I'm not convinced that the privacy risks are 0. 
Anyway, blocking this domain hasn't caused any issues for us.

Add federatedml-pa.googleapis.com

---

AmazonFireTV.txt

This domain is hit pretty hard by alexa devices. Speculation is that it is an analytics or tracking domain (https://www.reddit.com/r/pihole/comments/9470m2/anyone_know_what_httpd3p8zr0ffa9t17cloudfrontnet/). 
I have not noticed any issues after blocking it.

Add alexa analytics domain

---

SmartTV-AGH.txt
SmartTV.txt

A recent updated broughts ads to the home screen of Android TV devices like the Nvidia Shield TV: https://www.techradar.com/news/nvidia-shield-tv-users-are-angry-about-ads-but-can-you-get-around-them
These entries disable the ads.

Block Android TV home screen ads

---

SmartTV.txt

Observed empirically with:
```bash
dig @8.8.8.8 +short {collect,usage}-{us,eu}-fy20{21,22}.myhomescreen.tv
```

SmartTV: add 2021 and 2022 subdomains for myhomescreen.tv

---

SmartTV-AGH.txt
SmartTV.txt

Discovered outbound requests to api.thetake.com coming from my LG TV (requests happen every few minutes).
https://thetake.com redirects to https://thetake.ai/. This seems quite non-essential. According to their website, Samsung might be using this technology as well. This block has been tested for 1 week without issues.

Add TheTake.ai to SmartTV
